### ISSUE TITLE
Getting IllegalArgumentException during analyse.

### ISSUE THREAD

**Issue by zimnyx** [hcoles/highwheel#3]
mvn clean org.pitest:highwheel-maven:analyse -X
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /usr/local/lib/jvm/jdk1.8.0_31/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-37-generic", arch: "amd64", family: "unix"

...

[ERROR] Failed to execute goal org.pitest:highwheel-maven:1.0:analyse (default-cli) on project cltv: Execution default-cli of goal org.pitest:highwheel-maven:1.0:analyse failed. IllegalArgumentException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.pitest:highwheel-maven:1.0:analyse (default-cli) on project cltv: Execution default-cli of goal org.pitest:highwheel-maven:1.0:analyse failed.

...
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.pitest:highwheel-maven:1.0:analyse failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.IllegalArgumentException
	at org.pitest.highwheel.parser.asm.ClassReader.<init>(Unknown Source)
	at org.pitest.highwheel.parser.asm.ClassReader.<init>(Unknown Source)
	at org.pitest.highwheel.parser.asm.ClassReader.<init>(Unknown Source)
	at org.pitest.highwheel.bytecodeparser.ClassPathParser.parseClass(ClassPathParser.java:37)
	at org.pitest.highwheel.bytecodeparser.ClassPathParser.parse(ClassPathParser.java:27)
	at org.pitest.highwheel.maven.AnalyseMojo.analyse(AnalyseMojo.java:61)
	at org.pitest.highwheel.maven.BaseMojo.execute(BaseMojo.java:84)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more

**Comment by hcoles** [comment]
@zimnyx Thanks for the report.

The version of ASM highwheel currently depends on doesn't support Java 8. Should be a simple fix.

**Comment by turf00** [comment]
+1 on getting this corrected.

**Comment by hcoles** [comment]
Fixed in 1.2
